name: GPT Crawler CI

on:
    workflow_dispatch:
        inputs:
          URL:
            description: 'URL to scan'
            required: true
            default: 'https://drivingschool.wpmix.net/' # You can change the default value
          MATCH:
            description: 'SUBFOLDER TO SCAN'
            required: true
            default: '**' # You can change the default value        

jobs:
  build-and-crawl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Configure crawler
      run: |
        echo `import { Config } from "./src/config";
        import dotenv from "dotenv";
        import { Config } from "./src/config";
        
        
        dotenv.config();
        
        export const defaultConfig: Config = {
          url: process.env.URL || "${{ github.event.inputs.URL }}",
          match: process.env.MATCH || "${{ github.event.inputs.URL }}/${{ github.event.inputs.MATCH }}",
          maxPagesToCrawl: 50,
          outputFileName: "output.json",
        };` > ./src/config.ts
      env:
        URL: ${{ github.event.inputs.URL }}
        MATCH: ${{ github.event.inputs.MATCH }}
    - name: Run crawler
      run: npm start
