name: GPT Crawler CI

on:
    workflow_dispatch:
        inputs:
          URL:
            description: 'URL to scan'
            required: true
            default: 'https://drivingschool.wpmix.net/' # You can change the default value
          MATCH:
            description: 'SUBFOLDER TO SCAN'
            required: true
            default: '**' # You can change the default value        

jobs:
  build-and-crawl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Configure crawler
      run: |
        echo '
        import { Config } from "./src/config";
        var filename = "${{ github.event.inputs.URL }}"; // Corrected variable name
        filename = filename.replace(/(^\w+:|^)\/\//, "");
        filename = filename.replace(/\//g, "");

        export const defaultConfig: Config = {
          url: "${{ github.event.inputs.URL }}",
          match: "${{ github.event.inputs.URL }}/${{ github.event.inputs.MATCH }}",
          maxPagesToCrawl: 50,
          outputFileName: filename+".json",
          resourceExclusions: ["jpg","png"]
        };' > ./config.ts
      env:
        URL: ${{ github.event.inputs.URL }}
        MATCH: ${{ github.event.inputs.MATCH }}
    - name: Run crawler
      run: npm start
    - name: Prepare git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git config pull.rebase false
        git add -A
        git diff --cached --exit-code || git commit -m "GitHub Actions ($GITHUB_WORKFLOW)"
        git pull
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || true
